pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

include ':FtcRobotController'
include ':TeamCode'
include ':TestFramework'
include ':Season-BioBuzz'
include ':SimulatedApp'
include ':SimulatedApp-Testing'
include ':Dashboard'
include ':AndroidShims'
include ':CameraStream'
