package org.ngicollective.testframework.camera;

/**
 * The tag36h11 family's bit patterns: what a given AprilTag id actually looks like.
 *
 * <p>The renderer needs to draw tags, and the detector it is feeding will only accept genuine
 * codewords. Rather than derive the family here or call OpenCV at runtime, the patterns are
 * generated once and committed, which keeps this class and its tests dependency-free and runnable
 * on a plain JVM &mdash; the same reason the rest of this package avoids OpenCV.</p>
 *
 * <h2>Provenance</h2>
 *
 * <p>Generated by {@code tools/generate-tag36h11.py} from OpenCV's {@code DICT_APRILTAG_36h11}
 * predefined dictionary, which is the same dictionary FTC's repackaged OpenCV ships. Every one of
 * the 587 entries was validated during generation by rendering it and detecting it with apriltag3
 * itself: each read back as its own id at a Hamming distance of zero. Two properties are
 * re-asserted in {@code Tag36h11Test} so that a mangled table cannot pass review unnoticed: the
 * codewords are distinct, and the minimum Hamming distance between any two of them under any
 * rotation is 11 &mdash; which is what the "h11" in the family's name means.</p>
 *
 * <h2>Layout</h2>
 *
 * <p>A tag36h11 is {@value #CELLS_ACROSS} cells across: a 6x6 grid of data cells inside a
 * one-cell black border. That black square is what the detector finds, and what a tag's size
 * refers to, so a 3.25 in BioBuzz tag has 0.40625 in cells. Printed tags also carry a white quiet
 * zone outside the black border; its width is a printing choice rather than part of the code, so
 * it belongs to the renderer and not to this table.</p>
 *
 * <p>Codewords are packed row-major from the top-left of the data grid, most significant bit
 * first, with a set bit meaning a <em>white</em> cell.</p>
 */
public final class Tag36h11 {

    /** Width and height of the black square, in cells, including the black border. */
    public static final int CELLS_ACROSS = 8;

    /** Width and height of the data grid, in cells. */
    public static final int DATA_CELLS = 6;

    /** Number of ids in the family; ids run from 0 to one less than this. */
    public static final int FAMILY_SIZE = 587;

    private static final long[] CODEWORDS = {
            0x21A146BABL, 0x92D18FE9BL, 0x7089014BBL, 0x193979E27L,  // 0-3
            0x44153D3D7L, 0x35CD5B8CFL, 0xA10BA56A0L, 0x2B874A608L,  // 4-7
            0xB57FB8D44L, 0x4E20B5A64L, 0x61D897F2CL, 0xAB3469FFCL,  // 8-11
            0x594CA45C2L, 0xFA1C2D2E2L, 0x97C24B972L, 0x75928624AL,  // 12-15
            0x1CAAFE99AL, 0x3236DDC16L, 0x884E527D6L, 0x5771A8C7EL,  // 16-19
            0xF52925B81L, 0x2E59CC1A1L, 0x7FA58AB31L, 0xEB43384F9L,  // 20-23
            0x3913D5345L, 0xD79B1A3B5L, 0x0DFBE768DL, 0x5CD7A031DL,  // 24-27
            0xB9C8F7A4BL, 0x46987E06BL, 0x6E0C5D527L, 0x5BC567BB4L,  // 28-31
            0x1E6302BC2L, 0x8AC7D046AL, 0xA65FE2326L, 0x5400EB616L,  // 32-35
            0xF7A066836L, 0x2DD0AFDF6L, 0x3B9CB60B1L, 0xAD6A1CAF9L,  // 36-39
            0x93B62EFB5L, 0xBB210D93DL, 0xDEE55094BL, 0xA0CD1479BL,  // 40-43
            0x2A23ABB27L, 0x4F67F4B5FL, 0x58A815818L, 0x743427D64L,  // 44-47
            0x1DEC40874L, 0x892AB3A02L, 0x38D5742EEL, 0x0C43567A1L,  // 48-51
            0x5DB311CB1L, 0xC957CA1F9L, 0xA22457823L, 0x29ACE98F3L,  // 52-55
            0xCCC52C528L, 0xDA8B3578CL, 0xD5B4B9E36L, 0xAC9CDD3CEL,  // 56-59
            0xCBDAA8391L, 0x1986256B1L, 0xBAE6CC889L, 0xDF91B10E5L,  // 60-63
            0xA1A9D5A75L, 0x2B651AA9DL, 0x4D5C2E19DL, 0x5B163736BL,  // 64-67
            0xF753D60A8L, 0x5E84B37D2L, 0xFCE43A9F2L, 0xBB926D1A6L,  // 68-71
            0xED8D236E5L, 0x6AF846F37L, 0xEA56A5138L, 0x5D497146CL,  // 72-75
            0x470360ECAL, 0x8C4BCD67AL, 0x295F3901EL, 0xF6B577E97L,  // 76-79
            0x520602F5AL, 0xB5119492EL, 0x48E299AB7L, 0xB79F5737AL,  // 80-83
            0xA814C683EL, 0x2DA900583L, 0xD4ABA4797L, 0x982A0E65CL,  // 84-87
            0xF480CCC15L, 0x0B20EA732L, 0xA9506710AL, 0x0486E2EE1L,  // 88-91
            0xB0A972615L, 0xE73F3A257L, 0x17E205B98L, 0xEC9AB2B24L,  // 92-95
            0xD9339E076L, 0xEB8874F99L, 0x9420A55CCL, 0xE364FF992L,  // 96-99
            0x8A4CB8F0AL, 0xF72AEE766L, 0x73CC6B569L, 0xC99CA6A59L,  // 100-103
            0x366A0C535L, 0x509E51943L, 0xBA6D227D1L, 0xD2ACF163BL,  // 104-107
            0xD989FEF68L, 0x641707BB2L, 0xF9BD312ABL, 0x77739C207L,  // 108-111
            0x68BF8D1BFL, 0xDEDD84A6EL, 0x42EAEC49BL, 0x302B68D53L,  // 112-115
            0x4EBB930CEL, 0x439C5D9B5L, 0xE1FC9228DL, 0xF8A6A8D4AL,  // 116-119
            0xB53902A18L, 0xB163475EEL, 0xAD2F5AF29L, 0xAAB5DC850L,  // 120-123
            0xB3EC25786L, 0x4799C4405L, 0x8BC68DC04L, 0x702F15DDEL,  // 124-127
            0xB42293DA9L, 0x1ACAD0382L, 0x813363971L, 0x0E692AD70L,  // 128-131
            0x8AD05C5B9L, 0x85E654C1BL, 0x3D0AC2B3BL, 0x4BBFA0552L,  // 132-135
            0x722DDE306L, 0x369D1ACD2L, 0xA2D994E60L, 0x5FAD9139DL,  // 136-139
            0x57535AE96L, 0x5F5EF1D46L, 0xEBC3E6ACCL, 0x0A99C835DL,  // 140-143
            0x5463E49A5L, 0x25676893AL, 0xABED37064L, 0x59BDDED94L,  // 144-147
            0x64FA04C09L, 0x250E44E75L, 0xE58A374BCL, 0x24CAA5741L,  // 148-151
            0xE42CF6588L, 0x6EA238538L, 0xF75813025L, 0x0CEB33BBDL,  // 152-155
            0x786AE8670L, 0xF0DE8C969L, 0x26C81EFE6L, 0x69F489086L,  // 156-159
            0x3FBF92A4DL, 0xD6555A760L, 0x9CCAE236DL, 0xB256C16A3L,  // 160-163
            0xD78AC7221L, 0x2DC1FE262L, 0xAF2051090L, 0x932C08AFEL,  // 164-167
            0x53FECA775L, 0x5D292497AL, 0x2F101A22BL, 0xC6AD16B14L,  // 168-171
            0xD2ECA4B20L, 0xA6FA603D4L, 0x3057C3B69L, 0xE817B54D2L,  // 172-175
            0x40ABFC3E0L, 0xF53AD16E7L, 0x36F3A06E8L, 0x27782E418L,  // 176-179
            0x3E9062146L, 0x01FD7AD4EL, 0xC8765BC64L, 0xAD3D8215FL,  // 180-183
            0x96317A27EL, 0x05F813CA6L, 0x0E7ADC22EL, 0xBF52C4A50L,  // 184-187
            0x724F6AE2EL, 0x540FD7EA8L, 0x9C962F741L, 0x264042B01L,  // 188-191
            0x197CB7754L, 0x1F2BB850DL, 0xC87D6C2ADL, 0xDC8D2DEDEL,  // 192-195
            0xCB6B01738L, 0xBE4210368L, 0xBB4622A77L, 0x733226EF8L,  // 196-199
            0x4933ADE39L, 0x1F1C896C7L, 0x897665ABAL, 0x92F46BA12L,  // 200-203
            0x297981767L, 0xAD702CF8DL, 0x473198B90L, 0xEC2E8E06BL,  // 204-207
            0x36A1D6980L, 0xA5CE8650FL, 0x637870348L, 0xF3AB41D46L,  // 208-211
            0xE6032A8B5L, 0x4C11EEC73L, 0x261DE50D6L, 0x296616E32L,  // 212-215
            0x37CFF1A0AL, 0xC457847ABL, 0x776E52FF9L, 0x980819BB9L,  // 216-219
            0x50CB2B5D8L, 0x8B6918063L, 0x12D9C2CE9L, 0x158C2E738L,  // 220-223
            0x6B84015EAL, 0x67695DB9FL, 0x3E72745C1L, 0x01CA1A571L,  // 224-227
            0x22E7036F5L, 0xD5DCEDAE1L, 0x809532C5BL, 0xF7E4E9D54L,  // 228-231
            0x59D84F9CBL, 0xF42ED0851L, 0x5DB4A91FAL, 0x0D58E5B1FL,  // 232-235
            0x69FB9FA43L, 0x29BA51F60L, 0x587C67427L, 0xD8B9021EDL,  // 236-239
            0xBB594449EL, 0xAA231F35AL, 0x0D95943F4L, 0xDEC461257L,  // 240-243
            0x05A16930DL, 0xE2512EB58L, 0xAB48E2DC0L, 0x0CB68494FL,  // 244-247
            0x927A6B5B1L, 0xBB90F3450L, 0x632E8FAD0L, 0xC2EEAF2A7L,  // 248-251
            0x1EB2AF39DL, 0x511548C52L, 0x4693D5DE4L, 0x888E9161DL,  // 252-255
            0x68836FF4FL, 0x51BD2E441L, 0x7A0AC40E9L, 0x8BB762B4AL,  // 256-259
            0x1CAF83A1AL, 0xC2700BBBDL, 0xFB2ED09AAL, 0xF8520294EL,  // 260-263
            0x7AA104CA6L, 0x6A96D2BCBL, 0x28F2EC75EL, 0x607065EB4L,  // 264-267
            0x7AD9B3A8CL, 0x3572D6CBFL, 0xD426EFB8FL, 0x64EE4DBAAL,  // 268-271
            0x983D7A8F1L, 0x8CA31F499L, 0x025457B46L, 0xD53AE4149L,  // 272-275
            0x9D3C64396L, 0x795332EE5L, 0x70884D664L, 0x1DD3528D8L,  // 276-279
            0xD8E51D246L, 0xD6029CA38L, 0xD94AB610CL, 0x766BB8880L,  // 280-283
            0xFD0C6B319L, 0x3BFF8B9D1L, 0xE786F4D4EL, 0xD4E6B9B79L,  // 284-287
            0xCFA8BB369L, 0x20A4366C6L, 0x5CEFB9536L, 0x0F06B6605L,  // 288-291
            0xBB51D25E7L, 0xF7E262641L, 0x81FDA9855L, 0x2241DBC59L,  // 292-295
            0x56FB4B280L, 0xEDA64C6D0L, 0xCE7B080F4L, 0x6192EE7E9L,  // 296-299
            0x943FF5124L, 0x88B3BEADFL, 0x9B27E58D0L, 0xBE0B45FD2L,  // 300-303
            0x69FB3A72AL, 0x61383A832L, 0x6688639B3L, 0x54D01C992L,  // 304-307
            0x90B10C02AL, 0xF667FC6D1L, 0x7ACD75813L, 0x3ABD07F61L,  // 308-311
            0x543012473L, 0x067794D58L, 0xA855B1201L, 0x9CB4D7FDBL,  // 312-315
            0x31A193E6AL, 0x3DA3B76D4L, 0x4153F1E04L, 0x5544335B5L,  // 316-319
            0x92F61249DL, 0x269A35F8AL, 0x042677896L, 0x9487CDC6FL,  // 320-323
            0x4EA7E7D9CL, 0x2E367345BL, 0x3A5E8F304L, 0x76D9FAA77L,  // 324-327
            0x64E4EA1DFL, 0x12A7B434DL, 0x4973D9553L, 0xCDB418975L,  // 328-331
            0x8BDA76D2EL, 0xF54A4DEC8L, 0x811616F8AL, 0x4036F4E6BL,  // 332-335
            0x2736282A6L, 0xA413D229FL, 0x901FE4C17L, 0x9ABFCE56EL,  // 336-339
            0x2D325B9EFL, 0xD9901F6A9L, 0x3AA64FADEL, 0x65288D60BL,  // 340-343
            0x0A53E960BL, 0xE9E09C3E4L, 0x4D9B7863DL, 0xD98BB4833L,  // 344-347
            0x34B181ED7L, 0x5B373F490L, 0x8572B7B91L, 0x2C5D056A4L,  // 348-351
            0xE4671296DL, 0x2A08D6F78L, 0x452949C61L, 0x2501EC5B7L,  // 352-355
            0xB8F54779CL, 0xA3B7EA4B3L, 0x443D6B9B4L, 0xBE2DCB848L,  // 356-359
            0xB51FC47ECL, 0x6F38CF988L, 0x90F2FE934L, 0x07FD540ABL,  // 360-363
            0xEE53C3D08L, 0xF7098EBCAL, 0x65467C309L, 0xAE6FD797EL,  // 364-367
            0x8BC4739E9L, 0x971930FE4L, 0x9A752DF57L, 0xBD47FE53EL,  // 368-371
            0x6F1530928L, 0x5DE1CC489L, 0x111CE3DCDL, 0xA4C7E157CL,  // 372-375
            0x552691112L, 0x9D6511805L, 0x6663C1CB3L, 0xBFC594002L,  // 376-379
            0x3A3500387L, 0x76D4F679CL, 0x446F2667BL, 0x17AE59E97L,  // 380-383
            0x36132D63EL, 0x8E07492BFL, 0x188ACDDF1L, 0xED9052D02L,  // 384-387
            0x5B6BD01F5L, 0x84A4D070EL, 0xC9B2A3AF4L, 0xAB18852FCL,  // 388-391
            0x9DE918390L, 0x3576EE9E0L, 0xE8D00D210L, 0x709B5A95CL,  // 392-395
            0xA9022A314L, 0xA03EA2B9CL, 0x1E589EC5EL, 0x74470EEDDL,  // 396-399
            0x36BD44159L, 0xB7F8D2516L, 0xDCDE4BFA5L, 0x9EDA99C30L,  // 400-403
            0x8FFB98A8BL, 0x9AC777E71L, 0x8D0A53CB3L, 0xC9ED1DCEDL,  // 404-407
            0xC238535EAL, 0xEE4AA6437L, 0xCD8345A1EL, 0x5A19E05AEL,  // 408-411
            0x96D780D25L, 0xE2C885185L, 0xC5314F8DBL, 0xA47C37EE1L,  // 412-415
            0x1D82C6F8CL, 0x325C5C6C8L, 0x5D9D1BAE0L, 0x9549E075EL,  // 416-419
            0x8A6845C15L, 0xADF9F10FEL, 0x95CEF30B0L, 0x71933B20DL,  // 420-423
            0x1F0DE3A6FL, 0x596F5BBA6L, 0xCD61D9F34L, 0xA478AD328L,  // 424-427
            0xDADE4012FL, 0xD15764370L, 0x3A2BF5D22L, 0x2303E348DL,  // 428-431
            0x41B9BF9A9L, 0x5A4E93EE3L, 0x462B44512L, 0x4E01719C1L,  // 432-435
            0x73A0D9137L, 0x932B416DDL, 0xFF4B615A7L, 0x2C880F1ACL,  // 436-439
            0x6F3BB6AA1L, 0x476D21AE6L, 0xF9C290688L, 0x768111210L,  // 440-443
            0x623458F55L, 0xF31919E1FL, 0xEF47A7DD1L, 0xC6C777808L,  // 444-447
            0xEEC96F096L, 0x9B3C9BDAFL, 0x6FD432573L, 0x60E7D0AA9L,  // 448-451
            0x0651CDA34L, 0xE2ACC04E7L, 0x9460D1A22L, 0x82B79B177L,  // 452-455
            0x4EB189F4BL, 0xCBF9C3B1EL, 0x6F6C64841L, 0xE54E50A2EL,  // 456-459
            0x632F30F23L, 0xB3BB3DE6CL, 0x6331F5383L, 0xBCA1DAFE5L,  // 460-463
            0xD1816CAB9L, 0x0D8407ACAL, 0x794E1D7E5L, 0x92DE65442L,  // 464-467
            0x651497949L, 0x33F751712L, 0x3C9CE9195L, 0x7ECB81D7AL,  // 468-471
            0xEDE140178L, 0xC09B0EE2CL, 0x14E61F774L, 0x6D336649AL,  // 472-475
            0x865DD0880L, 0xF7214BFB8L, 0xD8B9C2E22L, 0x99A70737FL,  // 476-479
            0xC0ECF90C9L, 0xBB8B26E01L, 0x05678FCACL, 0x33B483834L,  // 480-483
            0xEB9D84B83L, 0x7CA277EA2L, 0x02AF5F66BL, 0x4A678C122L,  // 484-487
            0x121592BF3L, 0xCC82B48C9L, 0x77CBE90FCL, 0x5EF7D7931L,  // 488-491
            0x117947995L, 0x344D5F970L, 0xDF2F12E72L, 0x114277B37L,  // 492-495
            0x0B8FA73D5L, 0x36E16F423L, 0x057402B7EL, 0xC342423A7L,  // 496-499
            0x758C34DABL, 0x67DC61614L, 0x29B222068L, 0x7101AF0FAL,  // 500-503
            0x54D22BC75L, 0x908BA3AF9L, 0xEB68C9B51L, 0x2605D442CL,  // 504-507
            0x6AB88B7F4L, 0x207C7657DL, 0x377940D20L, 0xAC2EB77B6L,  // 508-511
            0x3E87318ECL, 0x47AFEA1AAL, 0x46DE35B74L, 0x48A36BA10L,  // 512-515
            0xF0711536BL, 0x963F87ED4L, 0xD83AB9965L, 0x7B2EB5A0FL,  // 516-519
            0xB6ADFAF32L, 0x87E07A4EAL, 0x7B4518F4EL, 0x9064A3738L,  // 520-523
            0x3C242CA12L, 0x96B25C4A4L, 0x8B01D83ACL, 0xE51CCEB25L,  // 524-527
            0x480F58DB0L, 0xBAE295867L, 0x89FC0FBA0L, 0xDD06475E9L,  // 528-531
            0xF7FE46B4CL, 0x43CEF026DL, 0x6393585A2L, 0x87B404456L,  // 532-535
            0x4FA47CBEAL, 0x7619F955AL, 0x51B9A1330L, 0x1533637C7L,  // 536-539
            0x7587A972AL, 0x60DE11622L, 0x7D4CE68AEL, 0xAF135E81CL,  // 540-543
            0x31C9B647CL, 0xAC43D8155L, 0xD853E1CFBL, 0x4FCDC5CF0L,  // 544-547
            0xEE696FD2DL, 0xB71618475L, 0xB9B4B8781L, 0x328579505L,  // 548-551
            0x95E947771L, 0x9AA0302E2L, 0xEC1828D17L, 0xBC5079635L,  // 552-555
            0x8785C1B79L, 0xD37AADB7AL, 0x817F02CE0L, 0xFD63DFB0AL,  // 556-559
            0x510AC1AF2L, 0x3D1EDF8D3L, 0xF4B73A402L, 0x37D789E9CL,  // 560-563
            0x8F11C77CAL, 0xC4BD036BEL, 0x7DFA995C9L, 0x7B14E8251L,  // 564-567
            0xCA070E7F4L, 0x5C22DBCD5L, 0xA0DB726C8L, 0x6B7776DE2L,  // 568-571
            0x80F58E748L, 0xE1AC1FF4AL, 0x1BBAEA85CL, 0x26AC557FCL,  // 572-575
            0xE5D1EF357L, 0x1F29D4E10L, 0x459FBB15BL, 0xD4B049559L,  // 576-579
            0x6CB70ACF8L, 0xF8617A518L, 0xC391DAC34L, 0x51235E2CCL,  // 580-583
            0x74407C4FEL, 0xDF1609A24L, 0xCED27DC17L,  // 584-586
    };

    private Tag36h11() {
    }

    /**
     * The 36-bit codeword for an id, packed row-major with a set bit meaning a white cell.
     *
     * @throws IllegalArgumentException if the id is not in the family, which is a configuration
     *     mistake worth failing loudly on: a detector would simply never report such a tag
     */
    public static long codeword(int id) {
        if (id < 0 || id >= FAMILY_SIZE) {
            throw new IllegalArgumentException("tag36h11 has ids 0.." + (FAMILY_SIZE - 1)
                    + "; got " + id);
        }
        return CODEWORDS[id];
    }

    /**
     * Whether a cell of the black square is white, for a cell address inside
     * {@link #CELLS_ACROSS}.
     *
     * <p>This is the question a rasteriser asks per pixel, so the border is answered here rather
     * than by every caller: row or column 0, or one less than {@link #CELLS_ACROSS}, is the black
     * border and is never white.</p>
     */
    public static boolean isWhite(int id, int row, int column) {
        if (row < 0 || row >= CELLS_ACROSS || column < 0 || column >= CELLS_ACROSS) {
            throw new IllegalArgumentException("cell (" + row + ", " + column + ") is outside a "
                    + CELLS_ACROSS + "x" + CELLS_ACROSS + " tag");
        }
        if (row == 0 || column == 0 || row == CELLS_ACROSS - 1 || column == CELLS_ACROSS - 1) {
            return false;
        }
        int index = (row - 1) * DATA_CELLS + (column - 1);
        return ((codeword(id) >>> (DATA_CELLS * DATA_CELLS - 1 - index)) & 1L) != 0L;
    }
}
