#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# One-time setup for publishing ftc-sim to Maven Central (ADR 0009, issue #31):
#   1. the org.ngi-collective namespace, verified by a DNS TXT record on ngi-collective.org
#   2. the project signing key, backed up offline and published to keyservers
#   3. the GitHub `release` environment on ngi-collective/ftc-sim, holding the secrets below
#
# Secrets written to the `release` environment, which the release workflow (#31) reads:
#   MAVEN_CENTRAL_USERNAME, MAVEN_CENTRAL_PASSWORD   Central Portal user token
#   SIGNING_KEY                                      ASCII-armoured private key
#   SIGNING_KEY_PASSWORD                             its passphrase
#   SIGNING_KEY_FINGERPRINT                          full fingerprint, for the workflow to derive ids
#
# Nothing secret is written to disk by this script. Public values (verification key, fingerprint,
# token expiry) go to ~/.config/ftc-sim/publishing.env so a re-run can pick up where it stopped.

TOTAL_STAGES=8

REPO="ngi-collective/ftc-sim"
DOMAIN="ngi-collective.org"
NAMESPACE="org.ngi-collective"
KEY_UID="ftc-sim releases <jarrod@ngi-collective.org>"
ENVIRONMENT="release"

ENV_FILE="$HOME/.config/ftc-sim/publishing.env"
mkdir -p "$(dirname "$ENV_FILE")"
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"

# set_env_secret NAME reads the value from stdin and stores it as a secret of the `release`
# environment, not of the repository: only a job that names the environment, and passes its
# approval, can read it. stdin rather than an argument so a private key never sits in a variable
# or on a command line.
set_env_secret() {
  local name="$1"
  if gh secret set "$name" --env "$ENVIRONMENT" --repo "$REPO" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$ENVIRONMENT/$name")
    printf '  %s✓ set%s %s secret %s\n' "$GREEN" "$RESET" "$ENVIRONMENT" "$name"
  else
    SKIPPED+=("$ENVIRONMENT secret $name (gh secret set $name --env $ENVIRONMENT --repo $REPO)")
    warn "could not set $name; see the summary at the end"
  fi
}

# Everything the stages below lean on, checked before anything is opened.
preflight() {
  local missing=()
  for tool in gh gpg dig curl; do
    command -v "$tool" >/dev/null 2>&1 || missing+=("$tool")
  done
  if (( ${#missing[@]} )); then
    printf '%s missing: %s. Install them and re-run.%s\n' "$RED" "${missing[*]}" "$RESET"
    exit 1
  fi
  if ! gh auth status >/dev/null 2>&1; then
    printf '%s gh is not signed in. Run: gh auth login%s\n' "$RED" "$RESET"
    exit 1
  fi
}

preflight
banner "ftc-sim: Maven Central publishing setup"

# ── 1. Namespace ──────────────────────────────────────────────────────────
stage "Central Portal: claim the $NAMESPACE namespace"
say "Maven Central only accepts uploads under a namespace you have proved you own."
say "Registering $NAMESPACE also covers $NAMESPACE.ftc-sim, the group ftc-sim uses."
open_url "https://central.sonatype.com/publishing/namespaces"
step "Sign in (or create an account) as jarrod@ngi-collective.org."
step "Click 'Add Namespace', enter $NAMESPACE, and click 'Submit'."
step "Next to the new namespace, click the clipboard icon by 'Verification Key'."
ask CENTRAL_VERIFICATION_KEY "Paste the verification key:"
write_env CENTRAL_VERIFICATION_KEY "$CENTRAL_VERIFICATION_KEY"

# ── 2. DNS ────────────────────────────────────────────────────────────────
stage "DNS: publish the verification key on $DOMAIN"
say "Add this record wherever $DOMAIN's DNS is managed"
note "(its nameservers today: $(dig +short NS "$DOMAIN" | tr '\n' ' '))"
printf '\n'
say "  ${BOLD}Type${RESET}   TXT"
say "  ${BOLD}Name${RESET}   $DOMAIN  (the apex: '@' in most consoles)"
say "  ${BOLD}Value${RESET}  $CENTRAL_VERIFICATION_KEY"
printf '\n'
note "An existing TXT record on the apex can stay; this one is added beside it."
pause "Press Enter once the record is saved."
while ! dig +short TXT "$DOMAIN" @8.8.8.8 | tr -d '"' | grep -qF "$CENTRAL_VERIFICATION_KEY"; do
  warn "not visible from 8.8.8.8 yet; DNS can take a few minutes"
  if confirm "Skip waiting and continue anyway?"; then
    SKIPPED+=("confirm the TXT record on $DOMAIN is visible before verifying the namespace")
    break
  fi
done
dig +short TXT "$DOMAIN" @8.8.8.8 | tr -d '"' | grep -qF "$CENTRAL_VERIFICATION_KEY" \
  && printf '  %s✓ TXT record visible%s\n' "$GREEN" "$RESET"
pause

# ── 3. Verify ─────────────────────────────────────────────────────────────
stage "Central Portal: verify the namespace"
open_url "https://central.sonatype.com/publishing/namespaces"
step "Next to $NAMESPACE, click 'Verify Namespace' and confirm."
step "Wait for its status to read Verified (refresh the page)."
if confirm "Does $NAMESPACE show as Verified?"; then
  write_env CENTRAL_NAMESPACE_VERIFIED "yes"
  note "The TXT record can be deleted now if you want; Central does not re-check it."
else
  SKIPPED+=("verify $NAMESPACE in the Central Portal once DNS has propagated")
  warn "carry on; publishing will fail until it is verified"
fi
pause

# ── 4. GitHub repository and environment ──────────────────────────────────
stage "GitHub: the $REPO repository and its '$ENVIRONMENT' environment"
say "The signing key and the Central token live in an environment, not in the repository:"
say "only a job that names '$ENVIRONMENT' can read them, and only after you approve it."
if gh repo view "$REPO" >/dev/null 2>&1; then
  printf '  %s✓ %s exists%s\n' "$GREEN" "$REPO" "$RESET"
elif confirm "$REPO does not exist yet. Create it now as an empty public repository?"; then
  gh repo create "$REPO" --public \
    --description "FTC robot simulator and test framework. Not affiliated with or endorsed by FIRST." \
    >/dev/null
  printf '  %s✓ created %s%s\n' "$GREEN" "$REPO" "$RESET"
else
  printf '%s Stopping: the secrets need the repository. Re-run when it exists.%s\n' "$RED" "$RESET"
  exit 1
fi
REVIEWER_LOGIN=$(gh api user --jq .login)
REVIEWER_ID=$(gh api user --jq .id)
# You approve every release yourself, so self-review stays allowed; deployments are limited to
# release tags, so a branch push can never reach these secrets.
gh api -X PUT "repos/$REPO/environments/$ENVIRONMENT" --input - >/dev/null <<JSON
{
  "reviewers": [{ "type": "User", "id": $REVIEWER_ID }],
  "prevent_self_review": false,
  "deployment_branch_policy": { "protected_branches": false, "custom_branch_policies": true }
}
JSON
printf '  %s✓ environment %s, approved by %s%s\n' "$GREEN" "$ENVIRONMENT" "$REVIEWER_LOGIN" "$RESET"
for pattern in 'v*' 'season-*/v*'; do
  if gh api -X POST "repos/$REPO/environments/$ENVIRONMENT/deployment-branch-policies" \
       -f name="$pattern" -f type=tag >/dev/null 2>&1; then
    printf '  %s✓ deploys allowed from tags %s%s\n' "$GREEN" "$pattern" "$RESET"
  else
    note "tag rule $pattern already present (or could not be added; check the environment page)"
  fi
done
open_url "https://github.com/$REPO/settings/environments"
note "Check the page shows the reviewer and the two tag rules."
pause

# ── 5. Signing key ────────────────────────────────────────────────────────
stage "GPG: the ftc-sim release signing key"
say "A key for the project, not for you: it can be revoked or handed over without touching"
say "your own identity. Sign-only, as a primary key with no subkeys, because Central"
say "verifies signatures made by the primary key."
EXISTING_FPR=$(gpg --list-secret-keys --with-colons "$KEY_UID" 2>/dev/null \
  | awk -F: '/^fpr/ {print $10; exit}' || true)
if [[ -n "$EXISTING_FPR" ]] && confirm "A key for '$KEY_UID' already exists ($EXISTING_FPR). Use it?"; then
  SIGNING_KEY_FINGERPRINT="$EXISTING_FPR"
else
  step "gpg will ask for a passphrase. Use a long random one and save it in your password"
  step "manager now, under 'ftc-sim release signing key'. You will paste it again later."
  pause "Press Enter to generate the key."
  gpg --quick-generate-key "$KEY_UID" rsa4096 sign 2y
  SIGNING_KEY_FINGERPRINT=$(gpg --list-secret-keys --with-colons "$KEY_UID" \
    | awk -F: '/^fpr/ {print $10; exit}')
fi
write_env SIGNING_KEY_FINGERPRINT "$SIGNING_KEY_FINGERPRINT"
EXPIRES_EPOCH=$(gpg --list-keys --with-colons "$SIGNING_KEY_FINGERPRINT" | awk -F: '/^pub/ {print $7; exit}')
if [[ -z "$EXPIRES_EPOCH" ]]; then
  SIGNING_KEY_EXPIRES="never"
else
  # BSD date (macOS) takes -r seconds; GNU date (Linux, WSL) takes -d @seconds.
  SIGNING_KEY_EXPIRES=$(date -r "$EXPIRES_EPOCH" +%Y-%m-%d 2>/dev/null \
    || date -d "@$EXPIRES_EPOCH" +%Y-%m-%d)
fi
write_env SIGNING_KEY_EXPIRES "$SIGNING_KEY_EXPIRES"
note "Extend it before that date: gpg --quick-set-expire $SIGNING_KEY_FINGERPRINT 2y"
pause

# ── 6. Offline backup ─────────────────────────────────────────────────────
stage "GPG: back the key up offline"
say "If this machine dies, the backup is the only way to sign again or to revoke the key."
step "Plug in the drive you keep offline (or pick a folder you will move there)."
ask BACKUP_DIR "Folder to write the backup to:"
BACKUP_DIR="${BACKUP_DIR/#\~/$HOME}"
mkdir -p "$BACKUP_DIR"
gpg --armor --export-secret-keys "$SIGNING_KEY_FINGERPRINT" > "$BACKUP_DIR/ftc-sim-signing.private.asc"
gpg --armor --export "$SIGNING_KEY_FINGERPRINT" > "$BACKUP_DIR/ftc-sim-signing.public.asc"
REVOCATION="$HOME/.gnupg/openpgp-revocs.d/$SIGNING_KEY_FINGERPRINT.rev"
if [[ -f "$REVOCATION" ]]; then
  cp "$REVOCATION" "$BACKUP_DIR/ftc-sim-signing.revocation.rev"
else
  gpg --output "$BACKUP_DIR/ftc-sim-signing.revocation.rev" --gen-revoke "$SIGNING_KEY_FINGERPRINT"
fi
chmod 600 "$BACKUP_DIR"/ftc-sim-signing.*
printf '  %s✓ private key, public key and revocation certificate in %s%s\n' "$GREEN" "$BACKUP_DIR" "$RESET"
warn "The private key file is protected only by its passphrase. Keep the drive offline, and"
warn "delete these files from this machine if the folder is not the offline drive."
pause "Press Enter once the backup is somewhere safe."

# ── 7. Keyservers ─────────────────────────────────────────────────────────
stage "GPG: publish the public key"
say "Central checks signatures against public keyservers, so the public key has to be on one."
for server in keyserver.ubuntu.com keys.openpgp.org; do
  if gpg --keyserver "hkps://$server" --send-keys "$SIGNING_KEY_FINGERPRINT" >/dev/null 2>&1; then
    printf '  %s✓ sent to %s%s\n' "$GREEN" "$server" "$RESET"
  else
    SKIPPED+=("gpg --keyserver hkps://$server --send-keys $SIGNING_KEY_FINGERPRINT")
    warn "could not reach $server"
  fi
done
note "keys.openpgp.org emails jarrod@ngi-collective.org to publish the name on the key;"
note "approving that email is optional, since Central looks keys up by fingerprint."
if curl -fsS "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x$SIGNING_KEY_FINGERPRINT" >/dev/null 2>&1; then
  printf '  %s✓ keyserver.ubuntu.com serves the key%s\n' "$GREEN" "$RESET"
else
  note "keyserver.ubuntu.com does not serve it yet; it can take a few minutes"
fi
pause

# ── 8. Secrets ────────────────────────────────────────────────────────────
stage "GitHub: signing key and Central token into '$ENVIRONMENT'"
say "First the signing key, straight from gpg into GitHub; it never touches a file."
gpg --armor --export-secret-keys "$SIGNING_KEY_FINGERPRINT" | set_env_secret SIGNING_KEY
printf '%s' "$SIGNING_KEY_FINGERPRINT" | set_env_secret SIGNING_KEY_FINGERPRINT
ask_secret SIGNING_KEY_PASSWORD "Paste the key's passphrase (from your password manager):"
printf '%s' "$SIGNING_KEY_PASSWORD" | set_env_secret SIGNING_KEY_PASSWORD
unset SIGNING_KEY_PASSWORD
printf '\n'
say "Now the Central Portal token. It is shown once, so it goes into GitHub right here."
open_url "https://central.sonatype.com/usertoken"
step "Click 'Generate User Token'. Name it 'ftc-sim GitHub release' and pick an expiry."
step "Keep the dialog open until both values are pasted below."
ask_secret CENTRAL_TOKEN_USERNAME "Paste the token username:"
ask_secret CENTRAL_TOKEN_PASSWORD "Paste the token password:"
printf '%s' "$CENTRAL_TOKEN_USERNAME" | set_env_secret MAVEN_CENTRAL_USERNAME
printf '%s' "$CENTRAL_TOKEN_PASSWORD" | set_env_secret MAVEN_CENTRAL_PASSWORD
unset CENTRAL_TOKEN_USERNAME CENTRAL_TOKEN_PASSWORD
ask CENTRAL_TOKEN_EXPIRES "The expiry date you chose (YYYY-MM-DD), so you know when to rotate it:"
write_env CENTRAL_TOKEN_EXPIRES "$CENTRAL_TOKEN_EXPIRES"
printf '\n'
gh secret list --env "$ENVIRONMENT" --repo "$REPO" 2>/dev/null | sed 's/^/  /' || true
pause

finish
note "Public values are in $ENV_FILE. Re-run this script to rotate the token or re-send the key."
